# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ implementation of multivariate Normal probability density function for multiple inputs
#'
#'@param x data matrix of dimension p x n, p being the dimension of the 
#'data and n the number of data points 
#'@param mean mean vectors matrix of dimension p x K, K being the number of 
#'distributions for which the density probability has to be ealuated
#'@param varcovM list of length K of variance-covariance matrices, 
#'each of dimensions p x p
#'@return matrix of densities of dimension K x n
#'@export
#'@examples
#'microbenchmark(mvnpdf(x=matrix(1.96), mean=0, varcovM=diag(1)),
#'               mvnpdfC(x=matrix(1.96), mean=0, varcovM=diag(1)),
#'               mmvnpdfC(x=matrix(1.96), mean=matrix(0), varcovM=list(diag(1))),
#'               times=10000L)
#'microbenchmark(mvnpdf(x=matrix(rep(1.96,2), nrow=2, ncol=1), mean=c(0, 0), varcovM=diag(2)),
#'               mvnpdfC(x=matrix(rep(1.96,2), nrow=2, ncol=1), mean=c(0, 0), varcovM=diag(2)),
#'               mmvnpdfC(x=matrix(rep(1.96,2), nrow=2, ncol=1), 
#'                        mean=matrix(c(0, 0), nrow=2, ncol=1), 
#'                        varcovM=list(diag(2))),
#'               times=10000L)
#'microbenchmark(mvnpdf(x=matrix(c(rep(1.96,2),rep(0,2)), nrow=2, ncol=2), 
#'                      mean=list(c(0,0),c(-1,-1), c(1.5,1.5)),
#'                      varcovM=list(diag(2),10*diag(2), 20*diag(2))),
#'               mmvnpdfC(matrix(c(rep(1.96,2),rep(0,2)), nrow=2, ncol=2), 
#'                      mean=matrix(c(0,0,-1,-1, 1.5,1.5), nrow=2, ncol=3),
#'                      varcovM=list(diag(2),10*diag(2), 20*diag(2))),
#'               times=10000L)
#'
mmvnpdfC <- function(x, mean, varcovM) {
    .Call('NPflow_mmvnpdfC', PACKAGE = 'NPflow', x, mean, varcovM)
}

#' C++ implementation of multivariate skew Normal probability density function for multiple inputs
#'
#'@param x data matrix of dimension p x n, p being the dimension of the 
#'data and n the number of data points 
#'@param xi mean vectors matrix of dimension p x K, K being the number of 
#'distributions for which the density probability has to be ealuated
#'@param psi skew parameter vectors matrix of dimension p x K, K being the number of 
#'distributions for which the density probability has to be ealuated
#'@param varcovM list of length K of variance-covariance matrices, 
#'each of dimensions p x p
#'@return matrix of densities of dimension K x n
#'@export 
#'@examples
#'mmvsnpdfC(x=matrix(rep(1.96,2), nrow=2, ncol=1), 
#'          xi=matrix(c(0, 0)), psi=matrix(c(1, 1),ncol=1), sigma=list(diag(2))
#'          )
#'          
#'library(microbenchmark)
#'microbenchmark(mvsnpdf(x=matrix(rep(1.96,2), nrow=2, ncol=1), xi=c(0, 0), psi=c(1, 1), sigma=diag(2)),
#'               mmvsnpdfC(x=matrix(rep(1.96,2), nrow=2, ncol=1), xi=matrix(c(0, 0)), psi=matrix(c(1, 1),ncol=1), sigma=list(diag(2))),
#'               times=10000L
#'              )
#'microbenchmark(mvsnpdf(x=matrix(c(rep(1.96,2),rep(0,2)), nrow=2, ncol=2), 
#'                      xi=list(c(0,0),c(-1,-1), c(1.5,1.5)),
#'                      psi=list(c(0.1,0.1),c(-0.1,-1), c(0.5,-1.5)),
#'                      sigma=list(diag(2),10*diag(2), 20*diag(2))),
#'               mmvsnpdfC(matrix(c(rep(1.96,2),rep(0,2)), nrow=2, ncol=2), 
#'                      xi=matrix(c(0,0,-1,-1, 1.5,1.5), nrow=2, ncol=3), 
#'                      psi=matrix(c(0.1,0.1,-0.1,-1, 0.5,-1.5), nrow=2, ncol=3),
#'                      sigma=list(diag(2),10*diag(2), 20*diag(2))),
#'               times=10000L)
#'              
mmvsnpdfC <- function(x, xi, psi, sigma) {
    .Call('NPflow_mmvsnpdfC', PACKAGE = 'NPflow', x, xi, psi, sigma)
}

#' C++ implementation of multivariate Normal probability density function for multiple inputs
#'
#'@param x data matrix of dimension p x n, p being the dimension of the 
#'data and n the number of data points 
#'@param xi mean vectors matrix of dimension p x K, K being the number of 
#'distributions for which the density probability has to be ealuated
#'@param psi skew parameter vectors matrix of dimension p x K, K being the number of 
#'distributions for which the density probability has to be ealuated
#'@param varcovM list of length K of variance-covariance matrices, 
#'each of dimensions p x p
#'@param df vector of length K of degree of freedom parameters
#'@return matrix of densities of dimension K x n
#'@export
#'@examples
#'
#'#skew-normal limit
#'mmvsnpdfC(x=matrix(rep(1.96,2), nrow=2, ncol=1), 
#'          xi=matrix(c(0, 0)), psi=matrix(c(1, 1),ncol=1), sigma=list(diag(2))
#'          )
#'mvstpdf(x=matrix(rep(1.96,2), nrow=2, ncol=1),
#'        xi=c(0, 0), psi=c(1, 1), sigma=diag(2),
#'        df=100000000
#'        )
#'mmvstpdfC(x=matrix(rep(1.96,2), nrow=2, ncol=1), 
#'          xi=matrix(c(0, 0)), psi=matrix(c(1, 1),ncol=1), sigma=list(diag(2)),
#'          df=100000000
#'          )
#'          
#'#non-skewed limit         
#'mmvtpdfC(x=matrix(rep(1.96,2), nrow=2, ncol=1),
#'         mean=matrix(c(0, 0)), varcovM=list(diag(2)),
#'         df=10
#'         )
#'mmvstpdfC(x=matrix(rep(1.96,2), nrow=2, ncol=1), 
#'          xi=matrix(c(0, 0)), psi=matrix(c(0, 0),ncol=1), sigma=list(diag(2)),
#'          df=10
#'          )
#'          
#'microbenchmark(mvstpdf(x=matrix(rep(1.96,2), nrow=2, ncol=1), 
#'                       xi=c(0, 0), psi=c(1, 1), 
#'                       sigma=diag(2), df=10),
#'               mmvstpdfC(x=matrix(rep(1.96,2), nrow=2, ncol=1),
#'                         xi=matrix(c(0, 0)), psi=matrix(c(1, 1),ncol=1), 
#'                         sigma=list(diag(2)), df=10),
#'               times=10000L)
#'
mmvstpdfC <- function(x, xi, psi, sigma, df) {
    .Call('NPflow_mmvstpdfC', PACKAGE = 'NPflow', x, xi, psi, sigma, df)
}

#' C++ implementation of multivariate Normal probability density function for multiple inputs
#'
#'@param x data matrix of dimension p x n, p being the dimension of the 
#'data and n the number of data points 
#'@param mean mean vectors matrix of dimension p x K, K being the number of 
#'distributions for which the density probability has to be ealuated
#'@param varcovM list of length K of variance-covariance matrices, 
#'each of dimensions p x p
#'@param df vector of length K of degree of freedom parameters
#'@return matrix of densities of dimension K x n
#'@export
#'@examples
#'mvnpdf(x=matrix(1.96), mean=0, varcovM=diag(1))
#'mvtpdf(x=matrix(1.96), mean=0, varcovM=diag(1), df=10000000)
#'mmvtpdfC(x=matrix(1.96), mean=matrix(0), varcovM=list(diag(1)), df=10000000)
#'
#'mvtpdf(x=matrix(1.96), mean=0, varcovM=diag(1), df=10)
#'mmvtpdfC(x=matrix(1.96), mean=matrix(0), varcovM=list(diag(1)), df=10)
#'
#'
#'library(microbenchmark)
#'microbenchmark(mvtpdf(x=matrix(1.96), mean=0, varcovM=diag(1)),
#'               #mvpdfC(x=matrix(1.96), mean=0, varcovM=diag(1)),
#'               mmvtpdfC(x=matrix(1.96), mean=matrix(0), varcovM=list(diag(1))),
#'               times=10000L)
#'
mmvtpdfC <- function(x, mean, varcovM, df) {
    .Call('NPflow_mmvtpdfC', PACKAGE = 'NPflow', x, mean, varcovM, df)
}

#' C++ implementation of multivariate Normal probability density function
#' 
#'Based on the implementation from Nino Hardt and Dicko Ahmadou
#'http://gallery.rcpp.org/articles/dmvnorm_arma/ 
#'(accessed in August 2014)
#'
#'@param x data matrix
#'@param mean mean vector
#'@param varcovM variance covariance matrix
#'@return vector of densities
#'
#'@export
#'
#'@examples
#'mvnpdf(x=matrix(1.96), mean=0, varcovM=diag(1)
#'mvnpdfC(x=matrix(1.96), mean=0, varcovM=diag(1))
#'
#'library(microbenchmark)
#'microbenchmark(mvnpdf(x=matrix(1.96), mean=0, varcovM=diag(1)),
#'               mvnpdfC(x=matrix(1.96), mean=0, varcovM=diag(1)),
#'               times=10000L)     
#'               
mvnpdfC <- function(x, mean, varcovM) {
    .Call('NPflow_mvnpdfC', PACKAGE = 'NPflow', x, mean, varcovM)
}

#' C++ implementation of multivariate Normal probability density function for multiple inputs
#'
#'@param x data matrix of dimension p x n, p being the dimension of the 
#'data and n the number of data points 
#'@param c integer vector of cluster allocations with values from 1 to K
#'@param clustval vector unique values of c in the order corresponding to 
#'the storage of cluster parameters in \code{xi}, \code{psi}, and \code{varcovM}
#'@param xi mean vectors matrix of dimension p x K, K being the number of 
#'clusters
#'@param psi skew parameter vectors matrix of dimension p x K
#'@param varcovM list of length K of variance-covariance matrices, 
#'each of dimensions p x p
#'@param df vector of length K of degree of freedom parameters
#'@return vector of likelihood of length n
#'@export
#'@examples
#'
#'#skew-normal limit
#'mmvsnpdfC(x=matrix(rep(1.96,2), nrow=2, ncol=1), 
#'          xi=matrix(c(0, 0)), psi=matrix(c(1, 1),ncol=1), sigma=list(diag(2))
#'          )
#'mvstpdf(x=matrix(rep(1.96,2), nrow=2, ncol=1),
#'        xi=c(0, 0), psi=c(1, 1), sigma=diag(2),
#'        df=100000000
#'        )
#'mmvstpdfC(x=matrix(rep(1.96,2), nrow=2, ncol=1), 
#'          xi=matrix(c(0, 0)), psi=matrix(c(1, 1),ncol=1), sigma=list(diag(2)),
#'          df=100000000
#'          )
#'          
#'#non-skewed limit         
#'mmvtpdfC(x=matrix(rep(1.96,2), nrow=2, ncol=1),
#'         mean=matrix(c(0, 0)), varcovM=list(diag(2)),
#'         df=10
#'         )
#'mmvstpdfC(x=matrix(rep(1.96,2), nrow=2, ncol=1), 
#'          xi=matrix(c(0, 0)), psi=matrix(c(0, 0),ncol=1), sigma=list(diag(2)),
#'          df=10
#'          )
#'          
#'microbenchmark(mvstpdf(x=matrix(rep(1.96,2), nrow=2, ncol=1), 
#'                       xi=c(0, 0), psi=c(1, 1), 
#'                       sigma=diag(2), df=10),
#'               mmvstpdfC(x=matrix(rep(1.96,2), nrow=2, ncol=1),
#'                         xi=matrix(c(0, 0)), psi=matrix(c(1, 1),ncol=1), 
#'                         sigma=list(diag(2)), df=10),
#'               times=10000L)
#'
mvstlikC <- function(x, c, clustval, xi, psi, sigma, df, loglik) {
    .Call('NPflow_mvstlikC', PACKAGE = 'NPflow', x, c, clustval, xi, psi, sigma, df, loglik)
}

#' C++ implementation
#' 
#'
#'@param c list of MCMC partitions
#'
#'@export
#'
#'@examples
#'c <- list(c(1,1,2,3,2,3), c(1,1,1,2,3,3),c(2,2,1,1,1,1))
#'similarityMatC(sapply(c, "["))
#'
#'c2 <- list()
#'for(i in 1:100){
#'     c2 <- c(c2, list(rmultinom(n=1, size=3000, prob=rexp(n=3000))))
#'}
#'library(microbenchmark)
#'f <- function(){c3 <-sapply(c2, "[")
#'             similarityMatC(c3)}
#'microbenchmark(f(), time=1L)
#'
similarityMatC <- function(c) {
    .Call('NPflow_similarityMatC', PACKAGE = 'NPflow', c)
}

